baseURL: 'https://frankphuongnguyen.github.io/frankphuong/'
languageCode: 'en-us'
title: 'Frank Phuong'
theme: 'PaperMod'

params:
  homeInfoParams:
    Title: Nguyen Huu Phuong (Frank) ğŸ™‹ğŸ»â€â™‚ï¸
    Content: A writer about Data | Engineering | Product | Design
  socialIcons:
    - name: "linkedin"
      url: "https://linkedin.com/in/frankphuongnguyen"
    - name: "facebook"
      url: "https://www.facebook.com/frankphuongnguyen"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

